package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


//ppp
public class  Giris_ekrani  extends javax.swing.JFrame  { 
    
    boolean musteri_girisi = false;
       boolean admin_girisi = false;
       String onlineolankimlik ;
   
    /**
     * Creates new form giris_ekrani0
     */
    public Giris_ekrani() {
        initComponents();
          this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_ekranikapat = new javax.swing.JLabel();
        jLabel_ekranikucult = new javax.swing.JLabel();
        kullanici_kimlik = new javax.swing.JTextField();
        kullanici_sifre = new javax.swing.JPasswordField();
        alan_bos1 = new javax.swing.JLabel();
        alan_bos0 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        musteri_button = new javax.swing.JRadioButton();
        admin_button = new javax.swing.JRadioButton();
        giris_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        yeni_kayit_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(230, 230, 230));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\MorCivciv\\Desktop\\STOK.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ekranikapat.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel_ekranikapat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikapat.setText("X");
        jLabel_ekranikapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikapatMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_ekranikapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 40));

        jLabel_ekranikucult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_ekranikucult.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikucult.setText("-");
        jLabel_ekranikucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikucultMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_ekranikucult, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 20, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        kullanici_kimlik.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        kullanici_kimlik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici_kimlikMouseClicked(evt);
            }
        });
        jPanel1.add(kullanici_kimlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 250, 38));

        kullanici_sifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici_sifreMouseClicked(evt);
            }
        });
        jPanel1.add(kullanici_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 250, 38));

        alan_bos1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        alan_bos1.setForeground(new java.awt.Color(255, 51, 51));
        alan_bos1.setText("  ");
        jPanel1.add(alan_bos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 210, 23));

        alan_bos0.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        alan_bos0.setForeground(new java.awt.Color(255, 51, 51));
        alan_bos0.setText("  ");
        jPanel1.add(alan_bos0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 23));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 90, 90));
        jLabel2.setText(" Kullanıcı Kimliği:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 28));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 90, 90));
        jLabel4.setText(" Kullanıcı Şifresi:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 250, 28));

        musteri_button.setBackground(new java.awt.Color(204, 204, 204));
        musteri_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        musteri_button.setForeground(new java.awt.Color(51, 51, 51));
        musteri_button.setText("Müşteri");
        musteri_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteri_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(musteri_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 32));

        admin_button.setBackground(new java.awt.Color(204, 204, 204));
        admin_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_button.setForeground(new java.awt.Color(51, 51, 51));
        admin_button.setText("Yönetici");
        admin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(admin_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, 32));

        giris_button.setBackground(new java.awt.Color(0, 51, 204));
        giris_button.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        giris_button.setForeground(new java.awt.Color(255, 255, 255));
        giris_button.setText("GİRİŞ");
        giris_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giris_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(giris_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 200, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Yeni Müşteriyseniz Sisteme Kayıt Olmak İçin");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 478, 252, 26));

        yeni_kayit_btn.setFont(new java.awt.Font("Sitka Heading", 2, 16)); // NOI18N
        yeni_kayit_btn.setForeground(new java.awt.Color(0, 0, 255));
        yeni_kayit_btn.setText("Buraya Tıklayınız");
        yeni_kayit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yeni_kayit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yeni_kayit_btnMouseClicked(evt);
            }
        });
        jPanel1.add(yeni_kayit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 120, 24));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 350, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteri_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteri_buttonActionPerformed
        if (musteri_button.isSelected()){
            admin_button.setSelected (false);
            musteri_girisi = true;
            admin_girisi = false;
        }
    }//GEN-LAST:event_musteri_buttonActionPerformed
   
    private void giris_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_buttonActionPerformed
        
        if (kullanici_kimlik.getText().trim().isEmpty() && kullanici_sifre.getText().trim().isEmpty()){
           alan_bos0.setText("Kullanıcı Alanı Boş Bırakılamaz");
           alan_bos1.setText("Parola Alanı Boş Bırakılamaz ");
       }
       else if (kullanici_kimlik.getText().trim().isEmpty()){
           alan_bos0.setText("Kullanıcı Alanı Boş Bırakılamaz");
       }
       else if (kullanici_sifre.getText().trim().isEmpty()){
           alan_bos1.setText("Parola Alanı Boş Bırakılamaz ");
       }
       else {
           if(admin_girisi==true){
           
           try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "Select * from hny_stok_takip.yonetici where yonetici_kimlik=? and yonetici_sifre=? ";
           PreparedStatement pst = conn.prepareStatement(sql);
           pst.setString(1, kullanici_kimlik.getText());
           pst.setString(2, kullanici_sifre.getText());
           ResultSet rs = pst.executeQuery();
           
           if(rs.next()){
               JOptionPane.showMessageDialog(null,"Kullanıcı Kimliği ve Parola Eşleştirildi !");
               
               try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn0 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String sql23 = "insert into hny_stok_takip.aktif_kullanici (sno,aktif_kimlik ,aktif_sifre) values (?,?,?) ";           
            PreparedStatement pstt = conn0.prepareStatement(sql23);

            pstt.setString(1, "1");
            pstt.setString(2, kullanici_kimlik.getText());
            pstt.setString(3, kullanici_sifre.getText());
            pstt.executeUpdate();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA OLUŞTU ");
           }   
               adminekrani ap = new adminekrani();
               ap.setVisible(true);
               ap.pack();
               ap.setLocationRelativeTo(null);
               ap.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
           }
           else {
               JOptionPane.showMessageDialog(null,"Kullanıcı Kimliği ve Parola Uyumsuz !");
           }
           conn.close();
       }
       
       catch(Exception e){
            JOptionPane.showMessageDialog(null,"Kullanıcı Kimliği ve Parola Uyumsuz !");
        }
    }
        else{
          if(musteri_girisi==true) {
        
              try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "Select * from hny_stok_takip.kayitli_musteri where giris_kimlik=? and giris_sifre=? ";
           
           
           PreparedStatement pst = conn1.prepareStatement(sql);
           pst.setString(1, kullanici_kimlik.getText());
           pst.setString(2, kullanici_sifre.getText());
           ResultSet rs = pst.executeQuery();
           
           if(rs.next()){
               JOptionPane.showMessageDialog(null,"Kullanıcı Kimliği ve Parola Eşleştirildi !");
                
             try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String sql23 = "insert into hny_stok_takip.aktif_kullanici (sno,aktif_kimlik ,aktif_sifre) values (?,?,?) ";           
            PreparedStatement pstt = conn.prepareStatement(sql23);

            pstt.setString(1, "1");
            pstt.setString(2, kullanici_kimlik.getText());
            pstt.setString(3, kullanici_sifre.getText());
            pstt.executeUpdate();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA OLUŞTU ");
          }   
                musteri_ekrani  ppp = new musteri_ekrani();
                ppp.setVisible(true);
                ppp.pack();
                ppp.setLocationRelativeTo(null);
                ppp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
           }
           else {
                 JOptionPane.showMessageDialog(null,"Kullanıcı Kimliği ve Parola Uyumsuz !");
           }
        }
       
       catch(Exception e){
       
           JOptionPane.showMessageDialog(null,"Bilinmeyen Bir Hata Meydana Geldi !");
       }
           }
           }
        }
    }//GEN-LAST:event_giris_buttonActionPerformed

    private void yeni_kayit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yeni_kayit_btnMouseClicked
        System.out.print(onlineolankimlik);        
        Yeni_kayit yk = new Yeni_kayit();
        yk.setVisible(true);
        yk.pack();
        yk.setLocationRelativeTo(null);
        yk.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_yeni_kayit_btnMouseClicked

    private void admin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_buttonActionPerformed
       if (admin_button.isSelected()){
            musteri_button.setSelected (false);
            musteri_girisi = false;
            admin_girisi = true;
        }
    }//GEN-LAST:event_admin_buttonActionPerformed

    private void jLabel_ekranikapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikapatMouseClicked
       try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String query = "DELETE FROM hny_stok_takip.aktif_kullanici where sno=1" ;
           PreparedStatement  pst = conn.prepareStatement(query );
           pst.executeUpdate();
           
        }
         catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU");    
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel_ekranikapatMouseClicked

    private void jLabel_ekranikucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_ekranikucultMouseClicked

    private void kullanici_kimlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici_kimlikMouseClicked
        alan_bos0.setText(""); 
    }//GEN-LAST:event_kullanici_kimlikMouseClicked

    private void kullanici_sifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici_sifreMouseClicked
       alan_bos1.setText("");
    }//GEN-LAST:event_kullanici_sifreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris_ekrani().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin_button;
    private javax.swing.JLabel alan_bos0;
    private javax.swing.JLabel alan_bos1;
    private javax.swing.JButton giris_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_ekranikapat;
    private javax.swing.JLabel jLabel_ekranikucult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kullanici_kimlik;
    private javax.swing.JPasswordField kullanici_sifre;
    private javax.swing.JRadioButton musteri_button;
    private javax.swing.JLabel yeni_kayit_btn;
    // End of variables declaration//GEN-END:variables
}

