/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MorCivciv
 */
public class musteri_update extends javax.swing.JFrame implements Goster {

    /**
     * Creates new form musteri_update
     */
    public musteri_update() {
        initComponents();
        show_user();
    }
    
    public ArrayList<User1> userList(){
        ArrayList<User1> usersList= new ArrayList<>();
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.kayitli_musteri ( musteri_no, giris_kimlik, giris_sifre, musteri_ad, musteri_soyad, musteri_telefon, musteri_eposta) values (?,?,?,?,?,?,?)";           
           String query1 = "SELECT kayitli_musteri.* , aktif_kullanici.aktif_kimlik FROM kayitli_musteri , aktif_kullanici where \n" +
"kayitli_musteri.giris_kimlik= aktif_kullanici.aktif_kimlik";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query1);
           
           User1 user ;
           while(rs.next()){
               user = new User1(rs.getString("musteri_no"),rs.getString("giris_kimlik"),rs.getString("giris_sifre"),rs.getString("musteri_ad"),rs.getString("musteri_soyad"),rs.getString("musteri_telefon"),rs.getString("musteri_eposta"));
               usersList.add(user);
            }
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU ");
       }
        return usersList;
    }
    
    public void show_user(){
         ArrayList<User1> list = userList() ;
         DefaultTableModel model = (DefaultTableModel)tablo.getModel();
         Object [] row = new Object[7];
            for(int i=0 ; i<list.size();i++){
                
                row[0] = list.get(i).getmusteri_no();
                row[1] = list.get(i).getgiris_kimlik();
                row[2] = list.get(i).getgiris_sifre();
                row[3] = list.get(i).getmusteri_ad();
                row[4] = list.get(i).getmusteri_soyad();
                row[5] = list.get(i).getmusteri_telefon();
                row[6] = list.get(i).getmusteri_eposta();
                model.addRow(row);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_ekranikapat = new javax.swing.JLabel();
        jLabel_ekranikucult = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kullanici_kimligi = new javax.swing.JTextField();
        kullanici_sifre = new javax.swing.JTextField();
        musteri_ad = new javax.swing.JTextField();
        musteri_soyad = new javax.swing.JTextField();
        eposta = new javax.swing.JTextField();
        personelsoyadi_g = new javax.swing.JLabel();
        personelsoyadi_g1 = new javax.swing.JLabel();
        personelsoyadi_g2 = new javax.swing.JLabel();
        personelsoyadi_g3 = new javax.swing.JLabel();
        personelsoyadi_g4 = new javax.swing.JLabel();
        telefon = new javax.swing.JTextField();
        personelsoyadi_g5 = new javax.swing.JLabel();
        yenipersonelekle_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MorCivciv\\Desktop\\STOKufakkk.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel_ekranikapat.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel_ekranikapat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikapat.setText("X");
        jLabel_ekranikapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikapatMouseClicked(evt);
            }
        });

        jLabel_ekranikucult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_ekranikucult.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikucult.setText("-");
        jLabel_ekranikucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikucultMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<<<");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(jLabel_ekranikucult)
                .addGap(18, 18, 18)
                .addComponent(jLabel_ekranikapat)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_ekranikapat, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addComponent(jLabel_ekranikucult)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 0, 600, -1));

        kullanici_kimligi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel1.add(kullanici_kimligi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 201, 31));

        kullanici_sifre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel1.add(kullanici_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 201, 31));

        musteri_ad.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel1.add(musteri_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 201, 31));

        musteri_soyad.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel1.add(musteri_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 201, 31));

        eposta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel1.add(eposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 201, 31));

        personelsoyadi_g.setBackground(new java.awt.Color(255, 255, 255));
        personelsoyadi_g.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelsoyadi_g.setForeground(new java.awt.Color(102, 102, 102));
        personelsoyadi_g.setText("Kullanıcı Şifresi:");
        jPanel1.add(personelsoyadi_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 31));

        personelsoyadi_g1.setBackground(new java.awt.Color(255, 255, 255));
        personelsoyadi_g1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelsoyadi_g1.setForeground(new java.awt.Color(102, 102, 102));
        personelsoyadi_g1.setText("Müşteri Adı:");
        jPanel1.add(personelsoyadi_g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, 31));

        personelsoyadi_g2.setBackground(new java.awt.Color(255, 255, 255));
        personelsoyadi_g2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelsoyadi_g2.setForeground(new java.awt.Color(102, 102, 102));
        personelsoyadi_g2.setText("Müşteri Soyadı:");
        jPanel1.add(personelsoyadi_g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, 31));

        personelsoyadi_g3.setBackground(new java.awt.Color(255, 255, 255));
        personelsoyadi_g3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelsoyadi_g3.setForeground(new java.awt.Color(102, 102, 102));
        personelsoyadi_g3.setText("E-posta:");
        jPanel1.add(personelsoyadi_g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, 31));

        personelsoyadi_g4.setBackground(new java.awt.Color(255, 255, 255));
        personelsoyadi_g4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelsoyadi_g4.setForeground(new java.awt.Color(102, 102, 102));
        personelsoyadi_g4.setText("Kullanıcı Kimliği:");
        jPanel1.add(personelsoyadi_g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, 31));

        telefon.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel1.add(telefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 201, 31));

        personelsoyadi_g5.setBackground(new java.awt.Color(255, 255, 255));
        personelsoyadi_g5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelsoyadi_g5.setForeground(new java.awt.Color(102, 102, 102));
        personelsoyadi_g5.setText("Telefon:");
        jPanel1.add(personelsoyadi_g5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, 31));

        yenipersonelekle_button.setBackground(new java.awt.Color(0, 51, 255));
        yenipersonelekle_button.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        yenipersonelekle_button.setForeground(new java.awt.Color(255, 255, 255));
        yenipersonelekle_button.setText("Kaydımı Güncelle");
        yenipersonelekle_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yenipersonelekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenipersonelekle_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(yenipersonelekle_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 293, 40));

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Giris kimlik", "Giris Şifre", "Müşteri Ad", "Müşteri Soyad", "Telefon", "E- posta", "SIRA NO"
            }
        ));
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yenipersonelekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenipersonelekle_buttonActionPerformed
       
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           int row = tablo.getSelectedRow();
           String value =( tablo.getModel().getValueAt(row,0).toString());
           String  ifade  = "UPDATE hny_stok_takip.kayitli_musteri SET  giris_kimlik=?, giris_sifre=?, musteri_ad=?, musteri_soyad=?, musteri_telefon=?, musteri_eposta=?   where musteri_no="+value ;
           PreparedStatement pstt = conn.prepareStatement(ifade );
           
            pstt.setString(1,kullanici_kimligi.getText() );
            pstt.setString(2,kullanici_sifre.getText() );
            pstt.setString(3,musteri_ad.getText() );
            pstt.setString(4,musteri_soyad.getText() );
            pstt.setString(5,telefon.getText() );
            pstt.setString(6,eposta.getText() );
           pstt.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)tablo.getModel();
           model.setRowCount(0);
           show_user();
           JOptionPane.showMessageDialog(null,"GÜNCELLEME BAŞARILI , TEKRAR GİRİŞ YAPINIZ!" );
            Giris_ekrani ge = new Giris_ekrani();
        ge.setVisible(true);
        ge.pack();
        ge.setLocationRelativeTo(null);
        ge.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
           
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA Bu Kullanıcı Zaten Sisteme Kayıtlı");
       }
    }//GEN-LAST:event_yenipersonelekle_buttonActionPerformed

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked
         int i = tablo.getSelectedRow();
        TableModel model = tablo.getModel();
        kullanici_kimligi.setText(model.getValueAt(i, 1).toString());
        kullanici_sifre.setText(model.getValueAt(i, 2).toString());
        musteri_ad.setText(model.getValueAt(i, 3).toString());
        musteri_soyad.setText(model.getValueAt(i, 4).toString());
        telefon.setText(model.getValueAt(i, 5).toString());
        //telefon_t.setText(model.getValueAt(i, 5).toString());
        eposta.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_tabloMouseClicked

    private void jLabel_ekranikapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikapatMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String query = "DELETE FROM hny_stok_takip.aktif_kullanici where sno=1" ;
            PreparedStatement  pst = conn.prepareStatement(query );
            pst.executeUpdate();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA OLUŞTU");
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel_ekranikapatMouseClicked

    private void jLabel_ekranikucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_ekranikucultMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        musteri_ekrani ae= new musteri_ekrani();
        ae.setVisible(true);
        ae.pack();
        ae.setLocationRelativeTo(null);
        ae.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteri_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteri_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteri_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteri_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteri_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eposta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_ekranikapat;
    private javax.swing.JLabel jLabel_ekranikucult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kullanici_kimligi;
    private javax.swing.JTextField kullanici_sifre;
    private javax.swing.JTextField musteri_ad;
    private javax.swing.JTextField musteri_soyad;
    private javax.swing.JLabel personelsoyadi_g;
    private javax.swing.JLabel personelsoyadi_g1;
    private javax.swing.JLabel personelsoyadi_g2;
    private javax.swing.JLabel personelsoyadi_g3;
    private javax.swing.JLabel personelsoyadi_g4;
    private javax.swing.JLabel personelsoyadi_g5;
    private javax.swing.JTable tablo;
    private javax.swing.JTextField telefon;
    private javax.swing.JButton yenipersonelekle_button;
    // End of variables declaration//GEN-END:variables
}
