/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author MorCivciv
 */
public class musterileri_listele extends javax.swing.JFrame implements Goster {

    /**
     * Creates new form musterileri_listele
     */
    public musterileri_listele() {
        initComponents();
        show_user();
    }
    
    public ArrayList<User1> userList(){
        ArrayList<User1> usersList= new ArrayList<>();
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.kayitli_musteri ( musteri_no, giris_kimlik, giris_sifre, musteri_ad, musteri_soyad, musteri_telefon, musteri_eposta) values (?,?,?,?,?,?,?)";           
           //PreparedStatement pst = conn.prepareStatement(sql);
           String query1 = "SELECT * FROM hny_stok_takip.kayitli_musteri";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query1);
           
           User1 user ;
           while(rs.next()){
               user = new User1(rs.getString("musteri_no"),rs.getString("giris_kimlik"),rs.getString("giris_sifre"),rs.getString("musteri_ad"),rs.getString("musteri_soyad"),rs.getString("musteri_telefon"),rs.getString("musteri_eposta"));
               usersList.add(user);
              
           }
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU");
       }
        return usersList;
    }
    
    public void show_user(){
         ArrayList<User1> list = userList() ;
         DefaultTableModel model = (DefaultTableModel)kayitli_musteri_tablosu.getModel();
         Object [] row = new Object[7];
            for(int i=0 ; i<list.size();i++){
                
                row[0] = list.get(i).getmusteri_no();
                row[1] = list.get(i).getgiris_kimlik();
                row[2] = list.get(i).getgiris_sifre();
                row[3] = list.get(i).getmusteri_ad();
                row[4] = list.get(i).getmusteri_soyad();
                row[5] = list.get(i).getmusteri_telefon();
                row[6] = list.get(i).getmusteri_eposta();
                model.addRow(row);
            }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        geri_tusu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        giriskimlik_t = new javax.swing.JTextField();
        girissifre_t = new javax.swing.JTextField();
        musteriadi_t = new javax.swing.JTextField();
        musterisoyadi_t = new javax.swing.JTextField();
        telefon_t = new javax.swing.JTextField();
        eposta_t = new javax.swing.JTextField();
        msil_tusu = new javax.swing.JButton();
        mguncelle_tusu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        musterino_t2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kayitli_musteri_tablosu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel_ekranikapat = new javax.swing.JLabel();
        jLabel_ekranikucult = new javax.swing.JLabel();
        arama_btn_kateg = new javax.swing.JComboBox();
        arama_btn = new javax.swing.JTextField();
        musterino_t1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        geri_tusu.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        geri_tusu.setForeground(new java.awt.Color(255, 255, 255));
        geri_tusu.setText("<<<");
        geri_tusu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geri_tusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geri_tusuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(geri_tusu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geri_tusu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Müşteri Adı:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Müşteri Giriş Şifresi:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Müşteri Giriş Kimliği:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Müşteri Soyadı:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Müşteri Telefon:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 180, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Müşteri E-posta:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 180, 30));

        giriskimlik_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(giriskimlik_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 250, 40));

        girissifre_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(girissifre_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 250, 40));

        musteriadi_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(musteriadi_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 250, 40));

        musterisoyadi_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(musterisoyadi_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 250, 40));

        telefon_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(telefon_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 250, 40));

        eposta_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(eposta_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 250, 40));

        msil_tusu.setBackground(new java.awt.Color(255, 0, 51));
        msil_tusu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        msil_tusu.setForeground(new java.awt.Color(255, 255, 255));
        msil_tusu.setText("Seçili Müşteriyi Sistemden Sil");
        msil_tusu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        msil_tusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msil_tusuActionPerformed(evt);
            }
        });
        jPanel2.add(msil_tusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 290, 40));

        mguncelle_tusu.setBackground(new java.awt.Color(51, 51, 255));
        mguncelle_tusu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mguncelle_tusu.setForeground(new java.awt.Color(255, 255, 255));
        mguncelle_tusu.setText("Seçili Müşterini Bilgilerini Güncelle");
        mguncelle_tusu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mguncelle_tusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mguncelle_tusuActionPerformed(evt);
            }
        });
        jPanel2.add(mguncelle_tusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 610, -1, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Müşteri No:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        musterino_t2.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musterino_t2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musterino_t2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 250, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 765));

        kayitli_musteri_tablosu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kayitli_musteri_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri No", "Giriş Kimliği", "Giriş Şifresi", "Müşteri Adı", "Müşteri Soyadı", "Telefon No", "E-posta"
            }
        ));
        kayitli_musteri_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayitli_musteri_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kayitli_musteri_tablosu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 750, 620));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel_ekranikapat.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel_ekranikapat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikapat.setText("X");
        jLabel_ekranikapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikapatMouseClicked(evt);
            }
        });

        jLabel_ekranikucult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_ekranikucult.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikucult.setText("-");
        jLabel_ekranikucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikucultMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(706, Short.MAX_VALUE)
                .addComponent(jLabel_ekranikucult, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ekranikapat)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_ekranikapat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jLabel_ekranikucult))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 770, 40));

        arama_btn_kateg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arama_btn_kateg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Giriş Kimliği", "Müşteri Adı", "Müşteri Soyadı", "Telefon No", "E-posta", "Müşteri No" }));
        arama_btn_kateg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(arama_btn_kateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 250, 40));

        arama_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arama_btn.setForeground(new java.awt.Color(102, 102, 102));
        arama_btn.setText("Aramak İstediğinizi Buraya Giriniz");
        arama_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arama_btnMouseClicked(evt);
            }
        });
        arama_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_btnKeyReleased(evt);
            }
        });
        jPanel1.add(arama_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 290, 40));

        musterino_t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(musterino_t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 80, 0, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Tablodaki Verilerden Arama Yapmak İçin Önce Sol Taraftan Arama Kriterini Belirleyiniz ve Arama Kısmına Yazınız.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 54, 620, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msil_tusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msil_tusuActionPerformed
        int emin = JOptionPane.showConfirmDialog(null,"silmek istediğinizden emin misiniz","Delete", JOptionPane.YES_NO_OPTION) ;
        if(emin==0){
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.kayitli_musteri ( musteri_no, giris_kimlik, giris_sifre, musteri_ad, musteri_soyad, musteri_telefon, musteri_eposta) values (?,?,?,?,?,?,?)";
           int row = kayitli_musteri_tablosu.getSelectedRow();
           String value =( kayitli_musteri_tablosu.getModel().getValueAt(row,0).toString());
           String query = "DELETE FROM hny_stok_takip.kayitli_musteri where musteri_no="+value ;
           PreparedStatement  pst = conn.prepareStatement(query );
           pst.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)kayitli_musteri_tablosu.getModel();
           model.setRowCount(0);
           show_user();
           
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA SİLME BAŞARISIZ");    
      
        } 
        }
    }//GEN-LAST:event_msil_tusuActionPerformed

    private void kayitli_musteri_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitli_musteri_tablosuMouseClicked
       int i = kayitli_musteri_tablosu.getSelectedRow();
        TableModel model = kayitli_musteri_tablosu.getModel();
        
        musterino_t2.setText(model.getValueAt(i, 0).toString());
        giriskimlik_t.setText(model.getValueAt(i, 1).toString());
        girissifre_t.setText(model.getValueAt(i, 2).toString());
        musteriadi_t.setText(model.getValueAt(i, 3).toString());
        musterisoyadi_t.setText(model.getValueAt(i, 4).toString());
        telefon_t.setText(model.getValueAt(i, 5).toString());
        eposta_t.setText(model.getValueAt(i, 6).toString());
        
    }//GEN-LAST:event_kayitli_musteri_tablosuMouseClicked

    private void mguncelle_tusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mguncelle_tusuActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.kayitli_musteri ( musteri_no, giris_kimlik, giris_sifre, musteri_ad, musteri_soyad, musteri_telefon, musteri_eposta) values (?,?,?,?,?,?,?)";
           int row = kayitli_musteri_tablosu.getSelectedRow();
           String value =( kayitli_musteri_tablosu.getModel().getValueAt(row,0).toString());
           String  ifade  = "UPDATE hny_stok_takip.kayitli_musteri SET  giris_kimlik=?, giris_sifre=?, musteri_ad=?, musteri_soyad=?, musteri_telefon=?, musteri_eposta=?   where musteri_no="+value ;
           PreparedStatement pstt = conn.prepareStatement(ifade );
           
            pstt.setString(1,giriskimlik_t.getText() );
            pstt.setString(2,girissifre_t.getText() );
            pstt.setString(3,musteriadi_t.getText() );
            pstt.setString(4,musterisoyadi_t.getText() );
            pstt.setString(5,telefon_t.getText() );
            pstt.setString(6,eposta_t.getText() );
           pstt.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)kayitli_musteri_tablosu.getModel();
           model.setRowCount(0);
           show_user();
            JOptionPane.showMessageDialog(null,"GÜNCELLEME BAŞARILI" );
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA Bu Kullanıcı Zaten Sisteme Kayıtlı");
       }
    }//GEN-LAST:event_mguncelle_tusuActionPerformed

    private void geri_tusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geri_tusuMouseClicked
        adminekrani ae= new adminekrani();
        ae.setVisible(true);
        ae.pack();
        ae.setLocationRelativeTo(null);
        ae.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_geri_tusuMouseClicked

    private void arama_btnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_btnKeyReleased
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            TableModel model = kayitli_musteri_tablosu.getModel();
        
            String arama = (String)arama_btn_kateg.getSelectedItem();
            if(arama=="Müşteri Soyadı"){
                   String yaz1 = arama_btn.getText();
                   String ara1 = "SELECT * FROM hny_stok_takip.kayitli_musteri WHERE musteri_soyad LIKE '"+yaz1+"%'";
                   PreparedStatement pstt = conn.prepareStatement(ara1);
                   ResultSet rs = pstt.executeQuery();
                   kayitli_musteri_tablosu.setModel(DbUtils.resultSetToTableModel(rs));
                   pstt.close();
                    
            }
             if (arama=="Giriş Kimliği"){   
                   String yaz2 = arama_btn.getText();
                   String ara2 = "SELECT * FROM hny_stok_takip.kayitli_musteri WHERE giris_kimlik LIKE '"+yaz2+"%'";
                   PreparedStatement pstt2 = conn.prepareStatement(ara2);
                   ResultSet rs1 = pstt2.executeQuery();
                   kayitli_musteri_tablosu.setModel(DbUtils.resultSetToTableModel(rs1));
                   pstt2.close();
                   
            }
            if(arama=="Telefon No"){
                  String yaz3 = arama_btn.getText();
                  String ara3 = "SELECT * FROM hny_stok_takip.kayitli_musteri WHERE musteri_telefon LIKE '"+yaz3+"%'";
                  PreparedStatement pstt3 = conn.prepareStatement(ara3);
                  ResultSet rs2 = pstt3.executeQuery();
                  kayitli_musteri_tablosu.setModel(DbUtils.resultSetToTableModel(rs2));
                  pstt3.close();
            }       
            if(arama=="Müşteri Adı"){
                  String yaz3 = arama_btn.getText();
                  String ara3 = "SELECT * FROM hny_stok_takip.kayitli_musteri WHERE musteri_ad LIKE '"+yaz3+"%'";
                  PreparedStatement pstt3 = conn.prepareStatement(ara3);
                  ResultSet rs2 = pstt3.executeQuery();
                  kayitli_musteri_tablosu.setModel(DbUtils.resultSetToTableModel(rs2));
                  pstt3.close();
            }
            if(arama=="E-posta"){
                  String yaz3 = arama_btn.getText();
                  String ara3 = "SELECT * FROM hny_stok_takip.kayitli_musteri WHERE musteri_eposta LIKE '"+yaz3+"%'";
                  PreparedStatement pstt3 = conn.prepareStatement(ara3);
                  ResultSet rs2 = pstt3.executeQuery();
                  kayitli_musteri_tablosu.setModel(DbUtils.resultSetToTableModel(rs2));
                  pstt3.close();
            }
            if(arama=="Müşteri No"){
                  String yaz3 = arama_btn.getText();
                  String ara3 = "SELECT * FROM hny_stok_takip.kayitli_musteri WHERE musteri_no LIKE '"+yaz3+"%'";
                  PreparedStatement pstt3 = conn.prepareStatement(ara3);
                  ResultSet rs2 = pstt3.executeQuery();
                  kayitli_musteri_tablosu.setModel(DbUtils.resultSetToTableModel(rs2));
                  pstt3.close();
            }
            }
       catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA ARAMA İŞLEMİ BAŞARISIZ OLDU");
        }
          
    }//GEN-LAST:event_arama_btnKeyReleased

    private void arama_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arama_btnMouseClicked
        arama_btn.setText("");
    }//GEN-LAST:event_arama_btnMouseClicked

    private void jLabel_ekranikapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikapatMouseClicked
         try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String query = "DELETE FROM hny_stok_takip.aktif_kullanici where sno=1" ;
           PreparedStatement  pst = conn.prepareStatement(query );
           pst.executeUpdate();
         }
        
         catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU");    
        }
        
        System.exit(0);
    }//GEN-LAST:event_jLabel_ekranikapatMouseClicked

    private void jLabel_ekranikucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_ekranikucultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musterileri_listele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musterileri_listele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musterileri_listele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musterileri_listele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musterileri_listele().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_btn;
    private javax.swing.JComboBox arama_btn_kateg;
    private javax.swing.JTextField eposta_t;
    private javax.swing.JLabel geri_tusu;
    private javax.swing.JTextField giriskimlik_t;
    private javax.swing.JTextField girissifre_t;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_ekranikapat;
    private javax.swing.JLabel jLabel_ekranikucult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kayitli_musteri_tablosu;
    private javax.swing.JButton mguncelle_tusu;
    private javax.swing.JButton msil_tusu;
    private javax.swing.JTextField musteriadi_t;
    private javax.swing.JTextField musterino_t1;
    private javax.swing.JLabel musterino_t2;
    private javax.swing.JTextField musterisoyadi_t;
    private javax.swing.JTextField telefon_t;
    // End of variables declaration//GEN-END:variables
}
