/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MorCivciv
 */
public class stok_listesi extends javax.swing.JFrame implements Goster  {

    /**
     * Creates new form stok_listesi
     */
    public stok_listesi() {
        initComponents();
        show_user();
    }
    
    public ArrayList<User2> userList(){
        ArrayList<User2> usersList= new ArrayList<>();
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.urunler2 (sira_no, kategori, barkod_no, urun_ad, urun_ut, urun_stt, urun_gramaj, satis_fiyati, urun_adeti) values (?,?,?,?,?,?,?,?,?)";           
           String query1 = "SELECT * FROM hny_stok_takip.urunler2";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query1);
           
           User2 user ;
           while(rs.next()){
               user = new User2(rs.getString("sira_no"),rs.getString("kategori"),rs.getString("barkod_no"),rs.getString("urun_ad"),rs.getString("urun_ut"),rs.getString("urun_stt"),rs.getString("urun_gramaj"),rs.getString("satis_fiyati"),rs.getString("urun_adeti"));
               usersList.add(user);
            }
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU");
       }
        return usersList;
    }
    
    public void show_user(){
         ArrayList<User2> list = userList() ;
         DefaultTableModel model = (DefaultTableModel)stok_tablosu.getModel();
         Object [] row = new Object[9];
            for(int i=0 ; i<list.size();i++){
                row[0] = list.get(i).getsira_no();
                row[1] = list.get(i).getkategori();
                row[2] = list.get(i).getbarkod_no();
                row[3] = list.get(i).geturun_ad();
                row[4] = list.get(i).geturun_ut();
                row[5] = list.get(i).geturun_stt();
                row[6] = list.get(i).geturun_gramaj();
                row[7] = list.get(i).getsatis_fiyati();
                row[8] = list.get(i).geturun_adeti();
                model.addRow(row);
            }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_ekranikapat = new javax.swing.JLabel();
        jLabel_ekranikucult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stok_tablosu = new javax.swing.JTable();
        kategorisel = new javax.swing.JComboBox();
        arama_btn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MorCivciv\\Desktop\\STOKufakkk.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<<<");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel_ekranikapat.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel_ekranikapat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikapat.setText("X");
        jLabel_ekranikapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikapatMouseClicked(evt);
            }
        });

        jLabel_ekranikucult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_ekranikucult.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikucult.setText("-");
        jLabel_ekranikucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikucultMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 647, Short.MAX_VALUE)
                .addComponent(jLabel_ekranikucult, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_ekranikapat)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_ekranikapat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_ekranikucult))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        stok_tablosu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stok_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sıra No", "Kategori", "Barkod No", "Ürün Adı", "Ürün Ü.T", "Ürün S.T.T", "Ürün Gramaj", "Satış Fiyati", "Ürün Stok Adeti"
            }
        ));
        stok_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stok_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stok_tablosu);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 800, 440));

        kategorisel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kategorisel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kategori", "Barkod No", "Ürün Adı", " " }));
        kategorisel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(kategorisel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 260, 40));

        arama_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arama_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_btnKeyReleased(evt);
            }
        });
        jPanel2.add(arama_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 330, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stok_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stok_tablosuMouseClicked
        int i = stok_tablosu.getSelectedRow();
        TableModel model = stok_tablosu.getModel();
        
    }//GEN-LAST:event_stok_tablosuMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        musteri_ekrani mp1= new musteri_ekrani();
        mp1.setVisible(true);
        mp1.pack();
        mp1.setLocationRelativeTo(null);
        mp1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel_ekranikapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikapatMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String query = "DELETE FROM hny_stok_takip.aktif_kullanici where sno=1" ;
            PreparedStatement  pst = conn.prepareStatement(query );
            pst.executeUpdate();
            
        }
          catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA OLUŞTU");
         }
        System.exit(0);
    }//GEN-LAST:event_jLabel_ekranikapatMouseClicked

    private void jLabel_ekranikucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_ekranikucultMouseClicked

    private void arama_btnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_btnKeyReleased
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            TableModel model = stok_tablosu.getModel();
        
        String arama = (String)kategorisel.getSelectedItem();
            if(arama=="Kategori"){
                String yaz1 = arama_btn.getText();
                   String ara1 = "SELECT * FROM hny_stok_takip.urunler2 WHERE kategori LIKE '"+yaz1+"%'";
                   PreparedStatement pstt = conn.prepareStatement(ara1);
                   ResultSet rs = pstt.executeQuery();
                   stok_tablosu.setModel(DbUtils.resultSetToTableModel(rs));
                   pstt.close();
                    
            }
             if (arama=="Barkod No"){   
                   String yaz2 = arama_btn.getText();
                   String ara2 = "SELECT * FROM hny_stok_takip.urunler2 WHERE barkod_no LIKE '"+yaz2+"%'";
                   PreparedStatement pstt2 = conn.prepareStatement(ara2);
                   ResultSet rs1 = pstt2.executeQuery();
                   stok_tablosu.setModel(DbUtils.resultSetToTableModel(rs1));
                   pstt2.close();
                   
            }
            if(arama=="Ürün Adı"){
                  String yaz3 = arama_btn.getText();
                  String ara3 = "SELECT * FROM hny_stok_takip.urunler2 WHERE urun_ad LIKE '%"+yaz3+"%'";
                  PreparedStatement pstt3 = conn.prepareStatement(ara3);
                  ResultSet rs2 = pstt3.executeQuery();
                  stok_tablosu.setModel(DbUtils.resultSetToTableModel(rs2));
                  pstt3.close();
            }       
          
         }
             catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA ARAMA İŞLEMİ BASARISIZ");

        }
         
    }//GEN-LAST:event_arama_btnKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stok_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stok_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stok_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stok_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stok_listesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_ekranikapat;
    private javax.swing.JLabel jLabel_ekranikucult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategorisel;
    private javax.swing.JTable stok_tablosu;
    // End of variables declaration//GEN-END:variables
}
