/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MorCivciv
 */
public class stok_islemleri extends javax.swing.JFrame implements Goster {
  /**
     * Creates new form stok_islemleri
     */
    public stok_islemleri() {
        initComponents();
        show_user();
    }
    
    public ArrayList<User2> userList(){
        ArrayList<User2> usersList= new ArrayList<>();
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.urunler2 (sira_no, kategori, barkod_no, urun_ad, urun_ut, urun_stt, urun_gramaj, satis_fiyati, urun_adeti) values (?,?,?,?,?,?,?,?,?)";           
           String query1 = "SELECT * FROM hny_stok_takip.urunler2";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query1);
           
           User2 user ;
           while(rs.next()){
               user = new User2(rs.getString("sira_no"),rs.getString("kategori"),rs.getString("barkod_no"),rs.getString("urun_ad"),rs.getString("urun_ut"),rs.getString("urun_stt"),rs.getString("urun_gramaj"),rs.getString("satis_fiyati"),rs.getString("urun_adeti"));
               usersList.add(user);
           }
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU ");
       }
        return usersList;
    }
    
    public void show_user(){
         ArrayList<User2> list = userList() ;
         DefaultTableModel model = (DefaultTableModel)stok_islem_tablosu.getModel();
         Object [] row = new Object[9];
            for(int i=0 ; i<list.size();i++){
                row[0] = list.get(i).getsira_no();
                row[1] = list.get(i).getkategori();
                row[2] = list.get(i).getbarkod_no();
                row[3] = list.get(i).geturun_ad();
                row[4] = list.get(i).geturun_ut();
                row[5] = list.get(i).geturun_stt();
                row[6] = list.get(i).geturun_gramaj();
                row[7] = list.get(i).getsatis_fiyati();
                row[8] = list.get(i).geturun_adeti();
                model.addRow(row);
            }
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        barkodno_t = new javax.swing.JTextField();
        urunadi_t = new javax.swing.JTextField();
        urunstt_t = new javax.swing.JTextField();
        gramaj_t = new javax.swing.JTextField();
        urunut_t = new javax.swing.JTextField();
        satisfiyati_t = new javax.swing.JTextField();
        birimadet_t = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        urun_ekle_btn = new javax.swing.JButton();
        urun_sil_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        guncelle_btn = new javax.swing.JButton();
        kategori_t1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        stok_islem_tablosu = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel_ekranikapat = new javax.swing.JLabel();
        jLabel_ekranikucult = new javax.swing.JLabel();
        kategorisel = new javax.swing.JComboBox();
        arama_btn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("<<<");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));
        jPanel2.add(barkodno_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 228, 35));
        jPanel2.add(urunadi_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 228, 35));
        jPanel2.add(urunstt_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 103, 35));
        jPanel2.add(gramaj_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 228, 35));
        jPanel2.add(urunut_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 107, 35));
        jPanel2.add(satisfiyati_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 106, 35));
        jPanel2.add(birimadet_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 104, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("  SN:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(" Birim Adet:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kategori:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Barkod No:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(" Ürünün Adı:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ürünün Ü.T.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" Ürünün S.T.T");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ürünün Gramajı:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText(" Satış Fiyatı:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 90, -1));

        urun_ekle_btn.setBackground(new java.awt.Color(0, 51, 255));
        urun_ekle_btn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        urun_ekle_btn.setForeground(new java.awt.Color(255, 255, 255));
        urun_ekle_btn.setText("Yeni Ürün Ekle");
        urun_ekle_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        urun_ekle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekle_btnActionPerformed(evt);
            }
        });
        jPanel2.add(urun_ekle_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 540, 200, -1));

        urun_sil_btn.setBackground(new java.awt.Color(255, 0, 0));
        urun_sil_btn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        urun_sil_btn.setForeground(new java.awt.Color(255, 255, 255));
        urun_sil_btn.setText("Ürünü Sistemden Sil");
        urun_sil_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        urun_sil_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_sil_btnActionPerformed(evt);
            }
        });
        jPanel2.add(urun_sil_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 640, 210, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        label.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 40));

        guncelle_btn.setBackground(new java.awt.Color(0, 153, 102));
        guncelle_btn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        guncelle_btn.setForeground(new java.awt.Color(255, 255, 255));
        guncelle_btn.setText("Mevcut Ürün Güncelle");
        guncelle_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guncelle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_btnActionPerformed(evt);
            }
        });
        jPanel2.add(guncelle_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        kategori_t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kategori_t1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1- Çikolata", "2- Kek / Bisküvi", "3- Soğuk Gıda", "4- Kraker" }));
        kategori_t1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(kategori_t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 690));

        stok_islem_tablosu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stok_islem_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sıra No:", "Kategori:", "Barkod No:", "Ürünün Adı:", "Ürün Ü.T", "Ürün S.T.T.", "Ürün Gramajı:", "Satış Fiyatı", "Birim Adet:"
            }
        ));
        stok_islem_tablosu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stok_islem_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stok_islem_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stok_islem_tablosu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 130, 956, 560));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel_ekranikapat.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel_ekranikapat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikapat.setText("X");
        jLabel_ekranikapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikapatMouseClicked(evt);
            }
        });

        jLabel_ekranikucult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_ekranikucult.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikucult.setText("-");
        jLabel_ekranikucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikucultMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(892, Short.MAX_VALUE)
                .addComponent(jLabel_ekranikucult, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_ekranikapat)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ekranikapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ekranikucult))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 960, 40));

        kategorisel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kategorisel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kategori", "Barkod No", "Ürün Adı", " " }));
        kategorisel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kategorisel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 260, 40));

        arama_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arama_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_btnKeyReleased(evt);
            }
        });
        jPanel1.add(arama_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 360, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urun_ekle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekle_btnActionPerformed
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String sql = "insert into hny_stok_takip.urunler2 ( kategori, barkod_no, urun_ad, urun_ut, urun_stt, urun_gramaj, satis_fiyati, urun_adeti) values (?,?,?,?,?,?,?,?)";           
            
            PreparedStatement pstt = conn.prepareStatement(sql);
           String kategorim = kategori_t1.getSelectedItem().toString();
           pstt.setString(1, kategorim);
            
            pstt.setString(2, barkodno_t.getText() );
            pstt.setString(3, urunadi_t.getText() );
            pstt.setString(4, urunut_t.getText() );
            pstt.setString(5, urunstt_t.getText() );
            pstt.setString(6, gramaj_t.getText() );
            pstt.setString(7, satisfiyati_t.getText() );
            pstt.setString(8, birimadet_t.getText() );
            pstt.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)stok_islem_tablosu.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"SİSTEME BAŞARIYLA EKLENDİ");
          
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA SİSTEME EKLENEMEDİ,ZATEN SİTEMDE VAROLABİLİR ?");
        }
    }//GEN-LAST:event_urun_ekle_btnActionPerformed

    private void stok_islem_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stok_islem_tablosuMouseClicked
        int i = stok_islem_tablosu.getSelectedRow();
        TableModel model = stok_islem_tablosu.getModel();
        
        String kateg = model.getValueAt(i, 1).toString();
            switch(kateg){
                case "1- Çikolata":
                    kategori_t1.setSelectedIndex(0);
                    break;
                case "2- Kek / Bisküvi":
                    kategori_t1.setSelectedIndex(1);
                    break;
                case "3- Soğuk Gıda":
                    kategori_t1.setSelectedIndex(2);
                    break;
                case "4- Kraker":
                    kategori_t1.setSelectedIndex(3);
                    break;    
            }
        
        label.setText(model.getValueAt(i, 0).toString());
        barkodno_t.setText(model.getValueAt(i, 2).toString());
        urunadi_t.setText(model.getValueAt(i, 3).toString());
        urunut_t.setText(model.getValueAt(i, 4).toString());
        urunstt_t.setText(model.getValueAt(i, 5).toString());
        gramaj_t.setText(model.getValueAt(i, 6).toString());
        satisfiyati_t.setText(model.getValueAt(i, 7).toString());
        birimadet_t.setText(model.getValueAt(i, 8).toString());
        
    }//GEN-LAST:event_stok_islem_tablosuMouseClicked

    private void urun_sil_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_sil_btnActionPerformed
         int emin = JOptionPane.showConfirmDialog(null,"silmek istediğinizden emin misiniz","Delete", JOptionPane.YES_NO_OPTION) ;
        if(emin==0){
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.urunler2 (sira_no, kategori, barkod_no, urun_ad, urun_ut, urun_stt, urun_gramaj, satis_fiyati, urun_adeti) values (?,?,?,?,?,?,?,?,?)"; 
           int row = stok_islem_tablosu.getSelectedRow();
           String value =( stok_islem_tablosu.getModel().getValueAt(row,0).toString());
           String query = "DELETE FROM hny_stok_takip.urunler2 where sira_no="+value ;
           PreparedStatement  pst = conn.prepareStatement(query );
           pst.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)stok_islem_tablosu.getModel();
           model.setRowCount(0);
           show_user();
           
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA SİLME BASARISIZ");    
      
        } 
     }  
        
    }//GEN-LAST:event_urun_sil_btnActionPerformed

    private void guncelle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_btnActionPerformed
       try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           int row = stok_islem_tablosu.getSelectedRow();
           String value =( stok_islem_tablosu.getModel().getValueAt(row,0).toString());
           String  ifade  = "UPDATE hny_stok_takip.urunler2 SET kategori=?, barkod_no=?, urun_ad=?, urun_ut=?, urun_stt=?, urun_gramaj=?, satis_fiyati=? ,urun_adeti=?  where sira_no="+value ;
           PreparedStatement pstt = conn.prepareStatement(ifade );
           
           String kategorim = kategori_t1.getSelectedItem().toString();
           pstt.setString(1, kategorim); 
           pstt.setString(2, barkodno_t.getText() );
            pstt.setString(3, urunadi_t.getText() );
            pstt.setString(4, urunut_t.getText() );
            pstt.setString(5, urunstt_t.getText() );
            pstt.setString(6, gramaj_t.getText() );
            pstt.setString(7, satisfiyati_t.getText() );
            pstt.setString(8, birimadet_t.getText() );
           pstt.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)stok_islem_tablosu.getModel();
           model.setRowCount(0);
           show_user();
           JOptionPane.showMessageDialog(null,"GÜNCELLEME BAŞARILI" );
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA GÜNCELLEME BAŞARISIZ");
       }
    }//GEN-LAST:event_guncelle_btnActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        adminekrani ae= new adminekrani();
        ae.setVisible(true);
        ae.pack();
        ae.setLocationRelativeTo(null);
        ae.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void arama_btnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_btnKeyReleased
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
             TableModel model = stok_islem_tablosu.getModel();

            String arama = (String)kategorisel.getSelectedItem();
            if(arama=="Kategori"){
                String yaz1 = arama_btn.getText();
                String ara1 = "SELECT * FROM hny_stok_takip.urunler2 WHERE kategori LIKE '"+yaz1+"%'";
                PreparedStatement pstt = conn.prepareStatement(ara1);
                ResultSet rs = pstt.executeQuery();
                stok_islem_tablosu.setModel(DbUtils.resultSetToTableModel(rs));
                pstt.close();
                
            }
            if (arama=="Barkod No"){
                String yaz2 = arama_btn.getText();
                String ara2 = "SELECT * FROM hny_stok_takip.urunler2 WHERE barkod_no LIKE '"+yaz2+"%'";
                PreparedStatement pstt2 = conn.prepareStatement(ara2);
                ResultSet rs1 = pstt2.executeQuery();
                stok_islem_tablosu.setModel(DbUtils.resultSetToTableModel(rs1));
                pstt2.close();
               
            }
            if(arama=="Ürün Adı"){
                String yaz3 = arama_btn.getText();
                String ara3 = "SELECT * FROM hny_stok_takip.urunler2 WHERE urun_ad LIKE '%"+yaz3+"%'";
                PreparedStatement pstt3 = conn.prepareStatement(ara3);
                ResultSet rs2 = pstt3.executeQuery();
                stok_islem_tablosu.setModel(DbUtils.resultSetToTableModel(rs2));
                pstt3.close();
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA ARAMA İŞLEMİ BASARISIZ");

        }

    }//GEN-LAST:event_arama_btnKeyReleased

    private void jLabel_ekranikapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikapatMouseClicked
         try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String query = "DELETE FROM hny_stok_takip.aktif_kullanici where sno=1" ;
           PreparedStatement  pst = conn.prepareStatement(query );
           pst.executeUpdate();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU");    
        } 
        System.exit(0);
    }//GEN-LAST:event_jLabel_ekranikapatMouseClicked

    private void jLabel_ekranikucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_ekranikucultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stok_islemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stok_islemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stok_islemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stok_islemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stok_islemleri().setVisible(true);
            }
        });
    }
//888
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_btn;
    private javax.swing.JTextField barkodno_t;
    private javax.swing.JTextField birimadet_t;
    private javax.swing.JTextField gramaj_t;
    private javax.swing.JButton guncelle_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ekranikapat;
    private javax.swing.JLabel jLabel_ekranikucult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategori_t1;
    private javax.swing.JComboBox kategorisel;
    private javax.swing.JLabel label;
    private javax.swing.JTextField satisfiyati_t;
    private javax.swing.JTable stok_islem_tablosu;
    private javax.swing.JButton urun_ekle_btn;
    private javax.swing.JButton urun_sil_btn;
    private javax.swing.JTextField urunadi_t;
    private javax.swing.JTextField urunstt_t;
    private javax.swing.JTextField urunut_t;
    // End of variables declaration//GEN-END:variables
}
