package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MorCivciv
 */
public class Yeni_kayit extends javax.swing.JFrame {
//String sirano11 = "999";
    /**
     * Creates new form Yeni_kayit
     */
    public Yeni_kayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_ekranikapat = new javax.swing.JLabel();
        jLabel_ekranikucult = new javax.swing.JLabel();
        kullanici_sifresi = new javax.swing.JTextField();
        personelkimligi_g = new javax.swing.JLabel();
        personelparola_g = new javax.swing.JLabel();
        personeltelefon_g = new javax.swing.JLabel();
        yenipersonelekle_button = new javax.swing.JButton();
        personeleposta_g = new javax.swing.JLabel();
        musteri_adi = new javax.swing.JTextField();
        musteri_soyadi = new javax.swing.JTextField();
        e_posta = new javax.swing.JTextField();
        kullanici_kimligi = new javax.swing.JTextField();
        personelsoyadi_g = new javax.swing.JLabel();
        personeltelefon_g1 = new javax.swing.JLabel();
        telefonn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MorCivciv\\Desktop\\STOKufakkk.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<<<");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, 60, 50));

        jLabel_ekranikapat.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel_ekranikapat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikapat.setText("X");
        jLabel_ekranikapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikapatMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel_ekranikapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 50));

        jLabel_ekranikucult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_ekranikucult.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikucult.setText("-");
        jLabel_ekranikucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikucultMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel_ekranikucult, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 20, -1));

        kullanici_sifresi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        personelkimligi_g.setBackground(new java.awt.Color(255, 255, 255));
        personelkimligi_g.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelkimligi_g.setForeground(new java.awt.Color(102, 102, 102));
        personelkimligi_g.setText("Müşteri Adı:");

        personelparola_g.setBackground(new java.awt.Color(255, 255, 255));
        personelparola_g.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelparola_g.setForeground(new java.awt.Color(102, 102, 102));
        personelparola_g.setText("Müşteri Soyadı:");

        personeltelefon_g.setBackground(new java.awt.Color(255, 255, 255));
        personeltelefon_g.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personeltelefon_g.setForeground(new java.awt.Color(102, 102, 102));
        personeltelefon_g.setText("Kullanıcı Şifresi:");

        yenipersonelekle_button.setBackground(new java.awt.Color(0, 51, 255));
        yenipersonelekle_button.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        yenipersonelekle_button.setForeground(new java.awt.Color(255, 255, 255));
        yenipersonelekle_button.setText("Sisteme Kayıt Ol");
        yenipersonelekle_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yenipersonelekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenipersonelekle_buttonActionPerformed(evt);
            }
        });

        personeleposta_g.setBackground(new java.awt.Color(255, 255, 255));
        personeleposta_g.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personeleposta_g.setForeground(new java.awt.Color(102, 102, 102));
        personeleposta_g.setText("E-posta Adresi:");

        musteri_adi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        musteri_soyadi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        e_posta.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        kullanici_kimligi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        personelsoyadi_g.setBackground(new java.awt.Color(255, 255, 255));
        personelsoyadi_g.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personelsoyadi_g.setForeground(new java.awt.Color(102, 102, 102));
        personelsoyadi_g.setText("Kullanıcı Kimliği:");

        personeltelefon_g1.setBackground(new java.awt.Color(255, 255, 255));
        personeltelefon_g1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        personeltelefon_g1.setForeground(new java.awt.Color(102, 102, 102));
        personeltelefon_g1.setText("Telefon No:");

        telefonn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(personelsoyadi_g)
                .addGap(32, 32, 32)
                .addComponent(kullanici_kimligi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(personeltelefon_g)
                .addGap(38, 38, 38)
                .addComponent(kullanici_sifresi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(personelkimligi_g)
                .addGap(56, 56, 56)
                .addComponent(musteri_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(personelparola_g)
                .addGap(39, 39, 39)
                .addComponent(musteri_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(personeltelefon_g1)
                .addGap(62, 62, 62)
                .addComponent(telefonn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(personeleposta_g)
                .addGap(53, 53, 53)
                .addComponent(e_posta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(yenipersonelekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personelsoyadi_g, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici_kimligi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personeltelefon_g, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici_sifresi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personelkimligi_g, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteri_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personelparola_g, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteri_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personeltelefon_g1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personeleposta_g, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_posta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(yenipersonelekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 600, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Giris_ekrani ge = new Giris_ekrani();
        ge.setVisible(true);
        ge.pack();
        ge.setLocationRelativeTo(null);
        ge.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void yenipersonelekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenipersonelekle_buttonActionPerformed
        
       if(kullanici_kimligi.getText().trim().isEmpty() )
        JOptionPane.showMessageDialog(null,"HATA BOŞ ALAN BIRAKILAMAZ "); 
       else if ( kullanici_sifresi.getText().trim().isEmpty() )
        JOptionPane.showMessageDialog(null,"HATA BOŞ ALAN BIRAKILAMAZ ");  
       else if ( musteri_adi.getText().trim().isEmpty() )
        JOptionPane.showMessageDialog(null,"HATA BOŞ ALAN BIRAKILAMAZ ");
         else if ( musteri_soyadi.getText().trim().isEmpty() )
        JOptionPane.showMessageDialog(null,"HATA BOŞ ALAN BIRAKILAMAZ ");      
        else if ( telefonn.getText().trim().isEmpty() )
        JOptionPane.showMessageDialog(null,"HATA BOŞ ALAN BIRAKILAMAZ ");  
        else if ( e_posta.getText().trim().isEmpty() )
        JOptionPane.showMessageDialog(null,"HATA BOŞ ALAN BIRAKILAMAZ ");
       else {
           try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String sql = "insert into hny_stok_takip.kayitli_musteri(   giris_kimlik , giris_sifre , musteri_ad , musteri_soyad  , musteri_telefon , musteri_eposta) values (?,?,?,?,?,?)";           
            PreparedStatement pstt = conn.prepareStatement(sql);

           pstt.setString(1, kullanici_kimligi.getText());
           pstt.setString(2, kullanici_sifresi.getText() );
           pstt.setString(3, musteri_adi.getText() );
           pstt.setString(4, musteri_soyadi.getText() );
           pstt.setString(5, telefonn.getText() );
           pstt.setString(6, e_posta.getText());
            pstt.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"BAŞARILI BİR ŞEKİLDE KAYIT OLDUNUZ");
            }
        
       catch(Exception e){
            int tita ;
            JOptionPane.showMessageDialog(null,"HATA Bu Kullanıcı Zaten Sisteme Kayıtlı");
            
        }
       }
       
        
    }//GEN-LAST:event_yenipersonelekle_buttonActionPerformed

    private void jLabel_ekranikapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikapatMouseClicked
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           
           String query = "DELETE FROM hny_stok_takip.aktif_kullanici where sno=1" ;
           PreparedStatement  pst = conn.prepareStatement(query );
           pst.executeUpdate();
           
        }
         catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU");    
        }
        
        System.exit(0);
    }//GEN-LAST:event_jLabel_ekranikapatMouseClicked

    private void jLabel_ekranikucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_ekranikucultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yeni_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yeni_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yeni_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yeni_kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yeni_kayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField e_posta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_ekranikapat;
    private javax.swing.JLabel jLabel_ekranikucult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField kullanici_kimligi;
    private javax.swing.JTextField kullanici_sifresi;
    private javax.swing.JTextField musteri_adi;
    private javax.swing.JTextField musteri_soyadi;
    private javax.swing.JLabel personeleposta_g;
    private javax.swing.JLabel personelkimligi_g;
    private javax.swing.JLabel personelparola_g;
    private javax.swing.JLabel personelsoyadi_g;
    private javax.swing.JLabel personeltelefon_g;
    private javax.swing.JLabel personeltelefon_g1;
    private javax.swing.JTextField telefonn;
    private javax.swing.JButton yenipersonelekle_button;
    // End of variables declaration//GEN-END:variables
}
