/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MorCivciv
 */
public class yonetici_update extends javax.swing.JFrame implements Goster {

    /**
     * Creates new form yonetici_update
     */
    public yonetici_update() {
        initComponents();
        
        try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String hh ="SELECT yonetici.sira_no FROM yonetici,aktif_kullanici WHERE yonetici.yonetici_kimlik=aktif_kullanici.aktif_kimlik";
            Statement stmt = null;
            stmt = conn4.createStatement();

            ResultSet rs = stmt.executeQuery(hh);
         
            while(rs.next()){
             int depo = Integer.parseInt(rs.getString("sira_no")); 
           if(depo==1  ) {
                 show_user();
           }
            }
        }
         catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA AKTİF KULLANICI HATASI  ");    
      
        } 
    }
    public ArrayList<User4> userList(){
        ArrayList<User4> usersList= new ArrayList<>();
        
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.yonetici (sira_no, yonetici_kimlik ,yonetici_sifre , yonetici_adi_soyadi , yonetici_telefon) values (?,?,?,?,?)";           
           String query1 = "SELECT * FROM hny_stok_takip.yonetici";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query1);
           
           User4 user ;
           while(rs.next()){
               user = new User4(rs.getString("sira_no"),rs.getString("yonetici_kimlik"),rs.getString("yonetici_sifre"),rs.getString("yonetici_adi_soyadi"),rs.getString("yonetici_telefon"));
               usersList.add(user);
           }
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA OLUŞTU");
       }
        return usersList;
    }
    
    public void show_user(){
         ArrayList<User4> list = userList() ;
         DefaultTableModel model = (DefaultTableModel)admin_tablo.getModel();
         Object [] row = new Object[5];
            for(int i=0 ; i<list.size();i++){
                row[0] = list.get(i).getsira_no();
                row[1] = list.get(i).getyonetici_kimlik();
                row[2] = list.get(i).getyonetici_sifre();
                row[3] = list.get(i).getyonetici_adi_soyadi();
                row[4] = list.get(i).getyonetici_telefon();
                model.addRow(row);
            }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_ekranikapat = new javax.swing.JLabel();
        jLabel_ekranikucult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        giris_sifre_t = new javax.swing.JTextField();
        telefon_t = new javax.swing.JTextField();
        giris_kimligi_t = new javax.swing.JTextField();
        ad_soyad_t = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        admin_tablo = new javax.swing.JTable();
        ekle_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        sil_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yetki = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MorCivciv\\Desktop\\STOKufakkk.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<<<");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 0, -1, 45));

        jLabel_ekranikapat.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel_ekranikapat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikapat.setText("X");
        jLabel_ekranikapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikapatMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_ekranikapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jLabel_ekranikucult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_ekranikucult.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ekranikucult.setText("-");
        jLabel_ekranikucult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ekranikucult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ekranikucultMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_ekranikucult, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -1, 20, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 600, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("  Yönetici Telefon:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 150, 30));

        giris_sifre_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(giris_sifre_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 170, 30));

        telefon_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(telefon_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 170, 30));

        giris_kimligi_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(giris_kimligi_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 170, 30));

        ad_soyad_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(ad_soyad_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 170, 30));

        admin_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sıra No:", "Giriş Kimlik:", "Giriş Şifre:", "Yönetici Adı Soyadı:", "Yönetici Telefon:"
            }
        ));
        admin_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(admin_tablo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 600, 260));

        ekle_btn.setBackground(new java.awt.Color(0, 51, 255));
        ekle_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ekle_btn.setForeground(new java.awt.Color(255, 255, 255));
        ekle_btn.setText("Yeni Yönetici Ekle");
        ekle_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ekle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ekle_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 180, 40));

        update_btn.setBackground(new java.awt.Color(255, 153, 0));
        update_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Bilgilerini Güncelle");
        update_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 180, 40));

        sil_btn.setBackground(new java.awt.Color(255, 0, 102));
        sil_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sil_btn.setForeground(new java.awt.Color(255, 255, 255));
        sil_btn.setText("Sistemden Sil");
        sil_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sil_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sil_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 180, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" Giriş Şifresi:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Giriş Kimliği:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(" Yönetici Adı Soyadı:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 140, 30));

        yetki.setText("jLabel7");
        jPanel1.add(yetki, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 10, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_btnActionPerformed
         try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String hh ="SELECT yonetici.sira_no FROM yonetici,aktif_kullanici WHERE yonetici.yonetici_kimlik=aktif_kullanici.aktif_kimlik";
            Statement stmt = null;
            stmt = conn4.createStatement();

            ResultSet rs = stmt.executeQuery(hh);
         
            while(rs.next()){
             int depo = Integer.parseInt(rs.getString("sira_no")); 
       
            if(depo==1  ) { 
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String sql = "insert into hny_stok_takip.yonetici (yonetici_kimlik ,yonetici_sifre , yonetici_adi_soyadi , yonetici_telefon ) values (?,?,?,?)";           
            PreparedStatement pstt = conn.prepareStatement(sql);

            pstt.setString(1, giris_kimligi_t.getText());
            pstt.setString(2, giris_sifre_t.getText() );
            pstt.setString(3, ad_soyad_t.getText() );
            pstt.setString(4, telefon_t.getText() );
          
            pstt.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)admin_tablo.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"YENİ KULLANICI SİSTEME BAŞARIYLA EKLENDİ  ");
          
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA Bu Kullanıcı Zaten Sisteme Kayıtlı");
        }
        }
        else {
          JOptionPane.showMessageDialog(null,"BU YETKİYE SADECE BAŞ YÖNETİCİ SAHİPTİR ");
        }
            }
          }
            catch(Exception de){
        JOptionPane.showMessageDialog(null,"HATA Bu Kullanıcı Zaten Sisteme Kayıtlı");
            }
    }//GEN-LAST:event_ekle_btnActionPerformed

    private void sil_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_btnActionPerformed
        
        int emin = JOptionPane.showConfirmDialog(null,"silmek istediğinizden emin misiniz","Delete", JOptionPane.YES_NO_OPTION) ;
        if(emin==0){
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.yonetici (yonetici_kimlik ,yonetici_sifre , yonetici_adi_soyadi , yonetici_telefon ) values (?,?,?,?)";      
           int row = admin_tablo.getSelectedRow();
           String value =( admin_tablo.getModel().getValueAt(row,0).toString());
           String query = "DELETE FROM hny_stok_takip.yonetici where sira_no="+value ;
           PreparedStatement  pst = conn.prepareStatement(query );
           pst.executeUpdate();
           DefaultTableModel model = (DefaultTableModel) admin_tablo.getModel();
           model.setRowCount(0);
           show_user();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA SİLME BASARISIZ");    
          } 
        }
       
         
    }//GEN-LAST:event_sil_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
       
          try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String hh ="SELECT yonetici.sira_no FROM yonetici,aktif_kullanici WHERE yonetici.yonetici_kimlik=aktif_kullanici.aktif_kimlik";
            Statement stmt = null;
            stmt = conn4.createStatement();

            ResultSet rs = stmt.executeQuery(hh);
         
            while(rs.next()){
             int depo = Integer.parseInt(rs.getString("sira_no")); 
         
         if(depo==1  ) {
              try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
           String sql = "insert into hny_stok_takip.yonetici (yonetici_kimlik ,yonetici_sifre , yonetici_adi_soyadi , yonetici_telefon ) values (?,?,?,?)";
           int row = admin_tablo.getSelectedRow();
           String value =( admin_tablo.getModel().getValueAt(row,0).toString());
           String  ifade  = "UPDATE hny_stok_takip.yonetici SET yonetici_kimlik=?, yonetici_sifre=?, yonetici_adi_soyadi=?, yonetici_telefon=?  where sira_no="+value ;
           PreparedStatement pstt = conn.prepareStatement(ifade );
           
            pstt.setString(1, giris_kimligi_t.getText());
            pstt.setString(2, giris_sifre_t.getText() );
            pstt.setString(3, ad_soyad_t.getText() );
            pstt.setString(4, telefon_t.getText() );
           
           pstt.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)admin_tablo.getModel();
           model.setRowCount(0);
           show_user();
           JOptionPane.showMessageDialog(null,"GÜNCELLEME  BAŞARILI " );
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"HATA Bu Kullanıcı Zaten Sisteme Kayıtlı");
       }
        }
        else {
          JOptionPane.showMessageDialog(null,"BU YETKİYE SADECE BAŞ YÖNETİCİ SAHİPTİR ");
        }
            }
          }
            catch(Exception de){
        JOptionPane.showMessageDialog(null,"HATA Bu Kullanıcı Zaten Sisteme Kayıtlı");
            }
    }//GEN-LAST:event_update_btnActionPerformed

    private void admin_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_tabloMouseClicked
        int i = admin_tablo.getSelectedRow();
        TableModel model = admin_tablo.getModel();
        
        yetki.setText(model.getValueAt(i,0).toString());
        giris_kimligi_t.setText(model.getValueAt(i, 1).toString());
        giris_sifre_t.setText(model.getValueAt(i, 2).toString());
        ad_soyad_t.setText(model.getValueAt(i, 3).toString());
        telefon_t.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_admin_tabloMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        adminekrani ae= new adminekrani();
        ae.setVisible(true);
        ae.pack();
        ae.setLocationRelativeTo(null);
        ae.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel_ekranikapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikapatMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hny_stok_takip","root","admin");
            String query = "DELETE FROM hny_stok_takip.aktif_kullanici where sno=1" ;
            PreparedStatement  pst = conn.prepareStatement(query );
            pst.executeUpdate();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"HATA OLUŞTU ");
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel_ekranikapatMouseClicked

    private void jLabel_ekranikucultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ekranikucultMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_ekranikucultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_soyad_t;
    private javax.swing.JTable admin_tablo;
    private javax.swing.JButton ekle_btn;
    private javax.swing.JTextField giris_kimligi_t;
    private javax.swing.JTextField giris_sifre_t;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_ekranikapat;
    private javax.swing.JLabel jLabel_ekranikucult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sil_btn;
    private javax.swing.JTextField telefon_t;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel yetki;
    // End of variables declaration//GEN-END:variables
}
